POST http://localhost:5000/api/auth/new
Content-Type: application/json

{
  "name": "eriel",
  "email": "erielmejias99@gmail.com",
  "password": "123456789"
}
###

POST http://localhost:5000/api/auth
Content-Type: application/json

{
  "name": "sheila",
  "email": "sheilafundora04@gmail.com",
  "password": "1"
}

###

GET http://localhost:5000/api/auth/renew
Content-Type: application/json

{
"name": "sheila",
  "email": "sheilafundora04@gamil.com",
"password": "123456789",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2RkZDEyZDlhMzZiMzEzMThjMDU5ZTAiLCJuYW1lIjoic2hlaWxhIiwiaWF0IjoxNjc1NDgyMTUwLCJleHAiOjE2NzU0ODkzNTB9.HUDuK6zBeUqFiodSKZH9r3mnaoEHwHSGGZMncjVf_iY"
}

###

