POST http://localhost:4000/api/events/
Content-Type: application/json

{
  "title": "asdasd",
  "notes": "cambiar titulo",
  "date_start": "Tue Jan 31 2023 14:00:00 GMT-0500 (Cuba Standard Time)",
  "date_end": "Tue Jan 31 2023 15:00:00 GMT-0500 (Cuba Standard Time)",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2Q5ZDdjZmM1YThkNDEyYzAxZTQ0ZWYiLCJuYW1lIjoic2hlaWxhIiwiaWF0IjoxNjc1MzU1NjU0LCJleHAiOjE2NzUzNjI4NTR9.4_OISEmPbwsUf8Vg4cWXA1K_cigQ90pDyW892YYd0oU"
}

###
GET http://localhost:4000/api/events
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2Q5ZDdjZmM1YThkNDEyYzAxZTQ0ZWYiLCJuYW1lIjoic2hlaWxhIiwiaWF0IjoxNjc1MzU1NjU0LCJleHAiOjE2NzUzNjI4NTR9.4_OISEmPbwsUf8Vg4cWXA1K_cigQ90pDyW892YYd0oU"
}

###

PUT http://localhost:4000/api/events/63dbe93fa110b03bb349e9a6
Content-Type: application/json

{
  "title": "asdasd nooo",
  "notes": " titulo cambiado",
  "date_start": "Tue Jan 31 2023 14:00:00 GMT-0500 (Cuba Standard Time)",
  "date_end": "Tue Jan 31 2023 15:00:00 GMT-0500 (Cuba Standard Time)",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2Q5ZDdjZmM1YThkNDEyYzAxZTQ0ZWYiLCJuYW1lIjoic2hlaWxhIiwiaWF0IjoxNjc1MzU1NjU0LCJleHAiOjE2NzUzNjI4NTR9.4_OISEmPbwsUf8Vg4cWXA1K_cigQ90pDyW892YYd0oU"
}

###

DELETE http://localhost:4000/api/events/63dbe93fa110b03bb349e9a9
Accept: application/json


###
